name: Build And Push Oracolo to Docker Hub
run-name: ${{ gitea.actor }} is runs ci pipeline
on: [ push ]

jobs:
  build-push-docker-image:
    runs-on: docker-dood
    #container: docker:latest
    #container: catthehacker/ubuntu:act-latest
    steps:
      - 
        uses: https://github.com/actions/hello-world-docker-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pastagringo/oracolo-docker