name: Build And Push Oracolo to Docker Hub
run-name: ${{ gitea.actor }} is runs ci pipeline
on: [ push ]

jobs:
  build:
    runs-on: docker
    steps:
      - 
        name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "pastagringo/oracolo-docker:latest"